### ISSUE TITLE
Add Lnkod to all spatial data

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#18]
We are missing Some columns in some of the datasets. 

lan.rda - Missing NUTS_ID, change column name "LnNamn" to "name"
NUTS_20M.rda Everything Fine
NUTS_10M.rda - Missing LnKod
kommuner.rda - Add stuff?

Should we add the other län variables to the kommuner dataset? Like Name, letter, nutsID? I'm not sure.

**Comment by Gcocca** [comment]
Issues are fixed. I would maintain the same structure for kommuner. It should be easy to join information if needed since we have one field (i.e. LnKod) shared between all the datasets.
