### ISSUE TITLE
Month in popup for canvas graph on cat salmonella

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#69]
Can you add the formatted "month/year" in the popup to the bars in the canvas.js graph for cat salmonella? 

Perhaps this line:
https://github.com/SVA-SE/svamap/blob/master/inst/salmonella_cat_timeslider/map.html#L212
and this line:
https://github.com/SVA-SE/svamap/blob/master/inst/salmonella_cat_timeslider/map.html#L221

could become something like:

						  toolTipContent: "Månad: {x}<br>Provtagna<Br>Total: {y}",

and

						  toolTipContent: "Månad: {x}<br>Positiva<Br>Total: {y}",

respectively. But with the date formatted in the same way you have the formatting in the map popup: "M/YYYY"

**Comment by trosendal** [comment]
Or perhaps the formatted date should be like in the axis of the graph "Jan-2019" but perhaps that is more difficult.

**Comment by hykim3594** [comment]
Done

**Comment by trosendal** [comment]
Great!
