### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#7]
I'm having trouble with the build process for this project on Travis. I made a bunch of commits yesterday to test different ways of installing the dependencies of `rgdal` on UBUNTU 12.04 but could not get it to work.

**Comment by LiNk-NY** [comment]
Did you install libhdf5-serial-dev? Looks like it's a dependency too.

**Comment by trosendal** [comment]
Still, get a strange dependency error:  

https://travis-ci.org/SVA-SE/svamap/builds/165903296

**Comment by LiNk-NY** [comment]
Shouldn't those packages be in `Imports` rather than `Depends` in your `DESCRIPTION`? 
Btw, the error doesn't seem as bad now as it was before. 
Try adding `rgdal` under `r_packages` to the `.travis.yml` file.

**Comment by trosendal** [comment]
Nice, that forced me to read over the documentation on Imports/Depends. I'm not sure that I understand it entirely, but, you're correct, the best practice in my case is to put the packages in `Imports`. Interestingly, it highlighted the fact that I had an `@example` in my documentation of a sample dataset that no longer worked because I needed the `sp` library to do the plotting. I removed the example as it was not really relevant.

**Comment by trosendal** [comment]
I'll have to look at the travis build log later today to see what happened with rgdal this time:

https://travis-ci.org/SVA-SE/svamap/builds/166016768

**Comment by LiNk-NY** [comment]
Seems like it's missing a config file 
```
configure: error: gdal-config not found or not executable.
```

**Comment by trosendal** [comment]
Got it. I used:

     r_binary_packages:
       - rgdal
       - rgeos

In the .travis.yml based on this [repo](https://github.com/kardinal-eros/sabotag-tools) which is also dependent on `rgdal`.

 @LiNk-NY Thanks for the discussion on this issue

**Comment by trosendal** [comment]
Build broken again... This appears to be another issue with the installation of one of rgdal or rgeos

**Comment by trosendal** [comment]
4c959a975e293c1298b60a31ecd784ecc461c639 closes the issue again
