### ISSUE TITLE
Draft of ASF page to Karl et al.

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#70]
Map updated only applies to Swedish data

- [x] Colours in map don't work after 2019
- [x] Remove canvas.js dependency (We only have a license to use it on one page)
- [x] The graph of EU pigs should only be shown if you select the layer in the map
- [x] Put the Swedish table above the map or make the whole page side-by-side. It is currently hard to look at everything at once. Perhaps this is a general layout improvement and needs to be further discussed. Ideas welcome.
- [x] Consider having 2 separate maps of positive cases in EU and one of sampling/boar density in Sweden. This could reduce the risk of misunderstanding that the dots in Sweden are not cases.
- [x] Show only 1 year of boar density in Sweden (Data on Mail from Thomas)
- [ ] Time series of domestic EU cases that are not in map.
- [x] Use random position in kommune as x,y coordinates for those missing x, y in domestic sampling of wild boars
- [x] Background layer with map with international boundaries that is clearer than the current

**Comment by hykim3594** [comment]
Does the time series of domestic EU cases (in the 7th task) mean EU Vildsvin layer? Or do we need to add another layer for that?

**Comment by trosendal** [comment]
I think we need the ADNS data for domestic cases in Europe in order to produce that graph. @LErnholm should be able to help with that. I wonder though how we will best show such a graph without generating confusion about what is in the map on the same page since that is only wild cases. Perhaps we should discuss this with the Karl et al. prior to changing the page. We can start with just getting the data and clean it up so we can add the graph or dataseries in the existing graph when requested.

**Comment by trosendal** [comment]
Timestamp of ADNS file for the update date of the ADNS layer

**Comment by hykim3594** [comment]
> Timestamp of ADNS file for the update date of the ADNS layer

Done
