### ISSUE TITLE
Cat Salmonella IE compatibility

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#76]
The cat salmonella page doesn't work in IE. This is a low priority issue. Browser usage stats indicate that about 3% of Swedish users visit pages from IE11.

**Comment by hykim3594** [comment]
@trosendal You fixed this bug before but I accidentally deleted the line recently. Now the cat salmonella page should work in IE.

**Comment by trosendal** [comment]
Ah, ok :+1: I was actually just reading about polyfill and didn't remember we had used it before :smile: .
