### ISSUE TITLE
CWD map language

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#78]
* We need to be able to toggle between Swedish and English.

Currently I have included the English as hidden elements. @hykim3594 Can you figure out how to modify the style of the elements of class `language_english` and `language_swedish` from .js? My thought was to put a button that flips the display = none state of those two classes on click. 

Or is there a better approach to this?

**Comment by hykim3594** [comment]
Here is the function to switch language. You need to add a button. 

`
function switchLanguage(d)
{
	if ( d.value === "English" ){
		d.value = "Svenska";
		$('[class="language_swedish"]').hide();
		$('[class="language_english"]').show();
	}
	else{
		d.value = "English";
		$('[class="language_english"]').hide();
		$('[class="language_swedish"]').show();
	}
};
`
