### ISSUE TITLE
Time Slider

### ISSUE THREAD

**Issue by trosendal** [SVA-SE/svamap#8]
I would consider using this jquery strategy to filter points by date:
https://github.com/dwilhelm89/LeafletSlider

**Comment by trosendal** [comment]
This was brought up again but a user request to view geographically data by time

**Comment by trosendal** [comment]
Now that the maps for AI and CWD have been published for a few months another request has come up for time filering of some kind. I have looked at the leaflet plugins for this and do not like the "in map" approach. I would like to slider to be outside the map, perhaps as follows:

1. use the JQuery timeslider to select a range. 
http://jsfiddle.net/ghusse/vM844/
http://ghusse.github.io/jQRangeSlider/demo.html
2. Use that range to subset the point data.
3. Redraw the layer:
https://github.com/Leaflet/Leaflet/issues/1416

Not really sure how to cobble that together yet.

**Comment by trosendal** [comment]
Another, simpler approach, that may satisfy the request in the short term is to add monthly layers. Break up the data by month and just add different layers. This is less than perfect for the map that currently has different layers for different species, like the CWD map. However different symbols could be used for that instead, so that layers only represent time.

**Comment by Wolrath** [comment]
Do we need to show the "Ej påvisad" in the timeline? Wouldn't it be easier to just make a separate, maybe simplified, map showing the spread of the disease?

**Comment by trosendal** [comment]
I was also thinking that as a short-term solution I could create two maps: 2016 and 2017. Then those maps could be placed in tabs so the user can view one and then the other. In this way the map itself doesn't matter, we just prefilter the data by time. Not super elegant, but it can be done pretty easily.

**Comment by Wolrath** [comment]
But what is it that we want to show? The spreading of the disease over a certain timeperiod (click on play-button to start the animation) or the total spreading up until today? If the latter - one map should be enough?

**Comment by trosendal** [comment]
Related to the description above about jquery slider the following will help:

Here is a sample of filtering the data by a button click:
    http://bl.ocks.org/zross/raw/47760925fcb1643b4225/
And the description on leaflet of how to use filter:
    http://leafletjs.com/examples/geojson/

**Comment by trosendal** [comment]
This issue has been addressed and a working test version of a map with a timeslider is [here](http://www.sva.se/Maps/AI_timeslider/map.html)

**Comment by trosendal** [comment]
Bug on time filtering. Cases that have two birds in the same location on different dates are not displayed

**Comment by trosendal** [comment]
Not a problem. If two cases fall in exactly the same location presently they are display on the map when selected by the first consecutive date. For the AI map this is fine since this is a very rare occurrence. In other cases this might be now ok.
